CREATE TABLE IF NOT EXISTS cache_audit (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actor TEXT NOT NULL,
  path TEXT NOT NULL,
  bytes INTEGER NOT NULL,
  reason TEXT NOT NULL
);
