CREATE TABLE IF NOT EXISTS server_artifacts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  region TEXT NOT NULL DEFAULT '',
  product TEXT NOT NULL DEFAULT '',
  locale TEXT NOT NULL DEFAULT '',
  build_key TEXT NOT NULL DEFAULT '',
  artifact_path TEXT NOT NULL UNIQUE,
  download_url TEXT NOT NULL DEFAULT '',
  mime_type TEXT NOT NULL DEFAULT '',
  size_bytes INTEGER NOT NULL DEFAULT 0,
  sha256 TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
